before:
  hooks:
    - go mod download

builds:
  - id: exec
    main: cmd/exec/main.go
    binary: executor_x_{{ .Os }}_{{ .Arch }}

    no_unique_dist_dir: true
    env: &env
      - CGO_ENABLED=0
    goos: &goos
      - linux
      - darwin
    goarch: &goarch
      - amd64
      - arm64
    goarm: &goarm
      - 7

snapshot:
  name_template: 'v{{ .Version }}'


release:
  # If set to true, will not auto-publish the release.
  draft: false
  prerelease: auto

  # Add extra pre-existing files to the release.
  # - build plugin index.yaml
  extra_files:
    - glob: ./plugins-index.yaml
