#!/usr/bin/env sh

echo 'level=info msg="Starting integration                                  integration=prometheus"'
echo 'level=info msg="Starting integration                                  integration=loki"'
echo 'level=info msg="Starting integration                                  integration=argocd"'
echo 'level=info msg="Starting integration                                  integration=segment"'
echo 'level=info msg="Starting server on address ":2113"            component="Lifecycle server"'
echo 'level=info msg="Analytics disabled via configuration settings."'
echo 'level=info msg="Registering filter "ObjectAnnotationChecker" (enabled: true)...  component="Filter Engine"'
echo 'level=info msg="Registering filter "NodeEventsChecker" (enabled: true)...  component="Filter Engine"'
echo 'level=info msg="Starting Plugin Manager for all enabled plugins" component="Plugin Manager'
echo 'level=info msg="Starting server on address ":2112"            component="Metrics server"'
echo 'level=warn msg="Failed to obtain secrets from Secret Manager: \"metric-token\" not found". component="Metrics server"'
echo 'level=error msg="While executing request: dial tcp 192.168.65.2:3000: wrong credentials: 403 Forbidden". component="Metrics server"'
echo 'level=info msg="Shutdown requested. Sending final message...  component=Controller"'
echo 'level=info msg="Shutdown requested. Finishing...              integration=prometheus"'
echo 'level=info msg="Shutdown requested. Finishing...              component="Metrics server"'
echo 'level=info msg="Shutdown requested. Finishing...              integration=loki"'
echo 'level=info msg="Shutdown requested. Finishing...              component="Lifecycle server"'