interactivity:
  - command:
      prefix: "helm list" # matches `helm list -A` too :)
      # flags: ..

      parser: "table" # YAML | JSON

    message:
      dropdowns:
        release: "{{ .Namespace }}/{{ .Name }}"
      actions:
        delete: "helm delete {{ .Name }} -n {{ .Namespace }}"
        notes: "helm get notes {{ .Name }} -n {{ .Namespace }}"

      preview: |
        Name:     {{ .Name }}
        Namespace: {{ .Revision }}
        STATUS:   {{ .Status }}
